### ISSUE TITLE
Small change to affiliation

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy-v5.0-paper#115]
Could my affiliation be changed please? 

Instead of:

https://github.com/astropy/astropy-v5.0-paper/blob/a3091a13af67d412737d0672c0177ac4f5937394/src/static/authors.tex#L341

```
\affiliation{Instituto de Astrof\'isica de La Plata, IALP (CONICET-UNLP), 1900 La Plata, Argentina}
```

**Comment by pllim** [comment]
Can you please PR this? Thanks!

**Comment by Gabriel-p** [comment]
Done!
