### ISSUE TITLE
Adding content on Data Central/Anglo-Australian Telescope

### ISSUE THREAD

**Issue by aragilar** [astropy/astropy-v5.0-paper#13]
It's not clear whether this would fit the paper, but I could add some content about one or more of:
* How Data Central uses astropy and its ecosystem to provide access to Australian surveys
* The addition of specutils support for most Australian optical surveys
* The use of astropy within the Anglo-Australian Telescope archive.

**Comment by adrn** [comment]
Thanks @aragilar and sorry for the delay! I think this would be great -- could you add 1–2 paragraphs (via pull request) to a new subsection in [the "connections to observatories and missions" section](https://github.com/astropy/astropy-v5.0-paper/blob/main/src/ms.tex#L386)? Thanks!

**Comment by adrn** [comment]
@aragilar Just checking in here: Would you still be interested in contributing this text? If so, we would need it soon (we are aiming to share a first draft of the paper at the end of next week).

**Comment by aragilar** [comment]
Yep, sorry, I'll try to post a PR this week.
