### ISSUE TITLE
Include latest version of figures in repo?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-v5.0-paper#25]
At the moment, to build the paper to edit a section I need to generate the figures but I wonder if this is unnecessary and if the generated version of the figures could be included in the repo and updated periodically?

**Comment by adrn** [comment]
Sorry for the delay. The idea behind the [showyourwork](https://showyourwork.readthedocs.io/) workflow is that any figures that are generated by code should be generated during the build, for reproducibility. So, this is experimental, but given that we're trying out this workflow, it doesn't make sense to include the figures in the repo.
