### ISSUE TITLE
What's-new Section

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy-v5.0-paper#30]
We (@mhvk and @nstarman) met to discuss our paper section. These are the categories we came up with, and some PRs that might make it into those sections.

### ✅ New (Sub)packages / features:
- [x]	[Time Series sub-package](https://docs.astropy.org/en/v3.2/whatsnew/3.2.html#whatsnew-3-2-timeseries)
    -	V3.1:   [New Box Least Squares Periodogram](https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html#new-box-least-squares-periodogram)
- [x] 	[Uncertainties and Distributions](https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html#whatsnew-3-1-uncertainty)
- [x]	[ERFA module is now it’s own thing](https://docs.astropy.org/en/v4.2/whatsnew/4.2.html#whatsnew-4-2-erfa)
    -	Obliquely tie in that units remains in astropy
-	~[Pytest plugin ecosystem](https://docs.astropy.org/en/older-docs-archive/v3.0/whatsnew/3.0.html#whatsnew-3-0-pytest-plugins)~
- [x]	[A new SpectralCoord class for representing and transforming spectral quantities](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-spectralcoord)
-	~[Velocity in Coordinates](https://docs.astropy.org/en/older-docs-archive/v3.0/whatsnew/3.0.html#whatsnew-3-0-velocities-skycoord-vel)~
- [x]	[WCS API](https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html#common-api-for-world-coordinate-systems)  : [A shared Python interface for World Coordinate Systems](https://github.com/astropy/astropy-APEs/blob/main/APE14.rst)
    -	Include APE reference

### ✅ Interoperability (w/in and w/out):
- [x] [Quantity + Numpy](https://docs.astropy.org/en/v4.0/whatsnew/4.0.html#whatsnew-4-0-quantity)
-	? [Added True Equator Mean Equinox (TEME) frame for satellite two-line ephemeris data](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-teme)
- [x]	[New Unified I/O architecture](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-io-unified)

- [x] Fits
    -	[Support for writing Dask arrays to FITS files](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-fitsdask)
    - [Fits Time Standards](https://docs.astropy.org/en/older-docs-archive/v3.0/whatsnew/3.0.html#whatsnew-3-0-fits-time-support)
        - GSOC interfacing with larger community

- [x] Table Column mixins
    - [HDF5] (https://docs.astropy.org/en/older-docs-archive/v3.0/whatsnew/3.0.html#whatsnew-3-0-hdf5-mixins)
    - [Support use of SkyCoord in table vstack, dstack, and insert_row](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-skycoord-stack)
    -	[Added support for dask arrays in tables](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-dask-in-table)
    -	[Added support for registering array-like objects as mixin columns](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-mixin-registry)

- [x] Table I/O
    -	[Support for reading and writing tables to QDP format](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-ascii-qdp-format)
    -	[Append table to existing FITS file](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-fits-append-table)
    - MRT [Support for reading and writing tables to MRT format](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-mrt-format-tables)
    -	GSOC interfacing with larger community
    -	[Support for reading and writing tables to Parquet format](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-parquet-tables)
    -	[Converting SkyCoord to QTable](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-skycoord-to-table)
    -	https://docs.astropy.org/en/v3.2/whatsnew/3.2.html#support-for-asdf-readers-writers-for-table-class

- [x] Cosmology:
    -	[Support for reading, writing, and converting Cosmology](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-cosmology-io)
    -	Redshift units & equivalency : [Cosmology units module](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-cosmology-units)

- [x] Modeling
    -	[Support for ASDF serialization of models](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-models-serialization)
    -	? Units in models : [Support for units on otherwise unitless models via the Model.coerce_units method.](https://docs.astropy.org/en/v4.1/whatsnew/4.1.html#whatsnew-4-1-models-units)

- [x] ECSV
    - [Support for multidimensional and object columns in ECSV](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-ecsv-subtypes)

### ✅ Precision, Accuracy, & Reproducibility:
- [x]	Constants and Units:
    -	[Improved Consistency of Physical Constants and Units](https://docs.astropy.org/en/v4.0/whatsnew/4.0.html#whatsnew-4-0-constants-units),
    -	SI/CODATA 2018 constants 
- [x]	Time: [Leap-seconds](https://docs.astropy.org/en/v4.0/whatsnew/4.0.html#whatsnew-4-0-time-leap-seconds)
- [x]	Coordinates:
    -	[Transformations to AltAz are now much more precise (and faster)](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-coordinates)
    -	[Ecliptic Transformations](https://docs.astropy.org/en/v3.2/whatsnew/3.2.html#additions-and-changes-to-ecliptic-transformations)
- [x]	Cosmology:
    -	Planck15, later superseded.
    -	[Pre-Publication Planck 2018 Cosmological Parameters](https://docs.astropy.org/en/v4.0/whatsnew/4.0.html#whatsnew-4-0-planck2018)
    -	Planck18 Accepted (replace above)
- [x] REPRODUCIBILITY NOTE: Can use old cosmologies and constants.
    -	For true reproducibility, pin your whole environment.
    -	WMAP1 & 3 Cosmologies

### ✅  Performance Enhancements:
-	[Faster cosmology calculations](https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html#whatsnew-3-1-faster-cosmology)
-	[Quantity](https://docs.astropy.org/en/v3.1.2/whatsnew/3.1.html#whatsnew-3-1-nocopy-unit)
-	Coordinate matching 
-	[Table](https://docs.astropy.org/en/v3.2/whatsnew/3.2.html#table-performance-improvements-and-change-in-meta-handling) , also [Improvements to Performance for Tables](https://docs.astropy.org/en/v4.0/whatsnew/4.0.html#whatsnew-4-0-table-performance),
-	[Time performance improvements](https://docs.astropy.org/en/v4.2/whatsnew/4.2.html#whatsnew-4-2-time-perf-imp),
-	[Transformations to AltAz are now much more precise (and faster)](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-coordinates)
-	[Improvements in making Astropy thread-safe](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-threadsafe)
    -	For Supercomputing?
-	Statistics: [Performance improvements to sigma clipping](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-sigma-clipping)

### ✅ Future Highlights / What to watch for : (Exists and being developed)
- [x]	[General masked class for Quantity and other ndarray subclasses](https://docs.astropy.org/en/v4.3post1/whatsnew/4.3.html#whatsnew-4-3-masked-class-quantity)
    -	[Support for masked quantity columns, including masked FITS columns with units](https://docs.astropy.org/en/stable/whatsnew/5.0.html#whatsnew-5-0-masked-quantity-columns)
-	? Uncertainties
-	Distributions

**Comment by adrn** [comment]
This looks excellent and comprehensive! If this feels like it is too long, I think it would be fine to remove 1–3 points from interoperability, precision, performance.

**Comment by mhvk** [comment]
@nstarman - unfortunately, I cannot edit the list above. I think I dealt with new features (including planned ones), except that I did not discuss proper motions and radial velocities, since those are from astropy 2.0, and hence in Paper II. I also wrote a performance section - which I kept very short, since I don't really think any of the details matter to the typical reader.

**Comment by mhvk** [comment]
p.s. I also pushed a few more commits which mostly have a few comments on your sections. Not sure this is the best way to do these, but obviously feel free to remove the commits as you deal with them!
