### ISSUE TITLE
Add paragraph describing Astropy + Outreachy

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-v5.0-paper#36]
See TODO item in "Inclusion, Diversity, and Equity Programs" section.

We currently do not have anyone assigned to contribute this text. @cadair would you be willing to add a few sentences about this?

**Comment by pllim** [comment]
Here, right?

https://github.com/astropy/astropy-v5.0-paper/blob/5cb0a9102595e7cdd59bae7c4a1d6b83deb649d4/src/ms.tex#L329

**Comment by adrn** [comment]
Closing this because I don't know the status, and no response from the coordinators.
