### ISSUE TITLE
Final vetting of authorship form submissions

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v5.0-paper#38]
Once all authorship form submissions are in, editors should go and vet the entries against the claims.

**Comment by adrn** [comment]
A reminder: We will send around one more call for authorship when we send around the paper draft this week.

**Comment by adrn** [comment]
I've vetted the author list - I just merged the author list PR, so it would be good for @pllim and @nmearl to look at the `authors.tex` file (over the next few days before submission at the end of this week).
