### ISSUE TITLE
Use non-numerical paper title?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v5.0-paper#4]
Paper 3 pointing to astropy 5 is super confusing for me. See running notes for Astropy Coordination Meeting 2021 Block 2.

**Comment by adrn** [comment]
I think "Paper 3" is just on the README, not the paper title...? If you want to change the README, go for it!

**Comment by astrofrog** [comment]
The solution is clearly to refer to it as Paper 5?

**Comment by pllim** [comment]
Looks like I am the only one who is confused? 🤷 Okie dokie then.
