### ISSUE TITLE
Add Moore Foundation in the acknowledgements section

### ISSUE THREAD

**Issue by aaryapatil** [astropy/astropy-v5.0-paper#41]
I asked the finance committee if we should acknowledge the relevant funding agencies in the acknowledgements section (in addition to mentioning them in the finance section). We all agreed that we should acknowledge the Moore Foundation for their financial support -- they are our major source of funding. This could be as simple as "We acknowledge the Gordon and Betty Moore foundation for their continued financial support". Else, the following sentence in the paper could be edited as: "We also thank NumFOCUS, the Python Software Foundation, and the Gordon and Betty Moore foundation...". Maybe this should also include an acknowledgement for the NASA grant -- note that the NASA grant was awarded in 2021 and its disbursement started (mostly) after v5.0.

We asked Gemini and Dunlap who provided relatively _smaller_ grants, and they are happy with their mentions in the finance section (Gemini asked us to add their standard acknowledgement).

**Comment by adrn** [comment]
Got it - thanks!
