### ISSUE TITLE
Maintenance window of LTS releases

### ISSUE THREAD

**Issue by zonca** [astropy/astropy-v5.0-paper#98]
The paper mentions LTS releases are maintained for "up to 2 years":
https://github.com/astropy/astropy-v5.0-paper/blob/13c52a2d7019a01a073f0077e2361661ffb007d2/src/ms.tex#L187-L189

However on the [referenced APE](https://zenodo.org/record/1043888) it says "at least 2 years".

**Comment by adrn** [comment]
Thanks!
